spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seubanco
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update # ou create-drop / validate / none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
